spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: siri
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update